### ISSUE TITLE
No module named 'addons.plugins.llms

### ISSUE THREAD

**Issue by louis26wq** [Soulter/llms#1]
l environment instead: https://pip.pypa.io/warnings/venv
[08-20 02:23:03] [INFO] [GOCQ]: 回复GOCQ消息: 指令调用错误: 
插件拉取载入失败。
跟踪: 
加载llms插件出现问题，原因No module named 'addons.plugins.llms'
![image](https://github.com/Soulter/llms/assets/80579925/70b88972-ca91-4969-a411-6ebeec47a518)

输入拉取插件的命令后返回的提示

查询plugins文件夹，发现在输入命令后生成了llms文件夹,里面也有文件

**Comment by Soulter** [comment]
程序的版本是最新的嘛

**Comment by Soulter** [comment]
~~原因可能是在启动程序的时候，路径不在QQChannelChatGPT目录下，可以先cd到这个目录下或者cd到QQChannelChatGPT文件夹所在的目录下~~

**Comment by louis26wq** [comment]
删除了文件夹，重新git clone https://github.com/Soulter/QQChannelChatGPT.git了文件夹
还是这个提示。
![image](https://github.com/Soulter/llms/assets/80579925/f095828d-0866-4a59-bbd8-5e115639fb9e)


试了下，拉goodplugins能成功，llms不行。
![image](https://github.com/Soulter/llms/assets/80579925/dcf50f40-f7fa-4ab8-82e1-603adcd50b30)

**Comment by Soulter** [comment]
知道问题了，使用这个：`plugin i https://github.com/Soulter/llms`，仓库名是小写的，而不是`plugin i https://github.com/Soulter/LLMS`。（然而Github仓库名在url上似乎不区分大小写）。程序这块的异常处理确实不够智能XD。

原来是README上写错了，已改正

**Comment by louis26wq** [comment]
thanks
