### ISSUE TITLE
在AstrBot 3.3.17版本上的工作问题

### ISSUE THREAD

**Issue by Alexme9125** [Soulter/llms#5]
在AstrBot 3.3.17版本上通过插件市场安装时，Bot首次启动时，插件在检测依赖的更新时不再工作，导致Bot无法启动。（且这个过程中没有发起任何网络请求）
该问题在Windows Server 2022（PowerShell）和macOS 15.1（Terminal）上均会出现。
![IMG_4095](https://github.com/user-attachments/assets/e6575bf6-10a1-41f3-97b5-b18de012edd6)
![IMG_4096](https://github.com/user-attachments/assets/2b433744-bcd0-4da1-a34f-5d7d15f2328f)

**Comment by Soulter** [comment]
这个可能是在某些环境下主线程在监听检查更新的子进程的标准输出流时被堵塞了，无法继续执行，应该是 AstrBot 的一个bug，晚点会修一下。

---
可以暂时这样解决：
1. 手动 python3 pip install -r <最后一条日志提供的路径>
如果还堵塞，再手动删除路径所对应的文件。

**Comment by Soulter** [comment]
请问 Python 版本是？我想复现一下这个问题

**Comment by Alexme9125** [comment]
> 请问 Python 版本是？我想复现一下这个问题

Python 3.12.7
